USE validation;

-- Copy of all logical applications
INSERT INTO
validation.logical_application
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_name_app,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
rde_data_backup_policies,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
app_id,
application_productnumber,
rde_data_approval_workflow,
rde_data_acronym_name,
rde_data_legacy_id,
rde_data_application_information_link,
rde_data_business_area,
rde_data_business_subarea,
rde_data_business_stakeholder_email,
rde_data_business_stakeholder_details,
rde_data_business_stakeholder_organization,
rde_data_key_business_user,
rde_data_countries,
rde_data_active_user_count,
rde_data_user_display_languages,
rde_data_app_managed_by,
rde_data_ism_mgd,
rde_data_business_er_approver_email,
rde_data_business_er_approver_details,
rde_data_application_manager_email,
rde_data_application_manager_details,
rde_data_solution_lead_email,
rde_data_solution_lead_details,
sm_data_technical_owner_details,
rde_data_outsource_comments,
rde_data_core_program,
rde_data_sw_package_notes,
rde_data_sw_release_notes,
rde_data_dev_language_and_tools,
rde_data_architecture,
rde_data_database_notes,
rde_data_service_window_proposed,
rde_data_service_window_comment,
rde_data_application_lifecycle_status,
rde_data_target_solution,
rde_data_decomm_date,
rde_data_original_decomm_date,
rde_data_decomm_target_date,
rde_data_decomm_notes,
rde_data_pw_linked_to_network_logon,
rde_data_pwd_change_process,
rde_data_primary_helpdesk,
rde_data_er_tool,
rde_data_incident_reporting_tool,
rde_data_service_request_tool,
rde_data_date_added_to_portfolio,
rde_data_ovsd_id,
rde_data_assetctr_id,
rde_data_change_management_tool,
rde_data_knowledge_management_tool,
rde_data_ticket_volume_er,
rde_data_ticket_volume_incident,
rde_data_ticket_volume_request,
rde_data_ticket_volume_change,
rde_data_it_support_staff,
rde_data_documentation_quality,
rde_data_notes,
rde_data_incl_in_scorecard,
rde_data_book_close_impact,
rde_data_core_program_previous,
rde_data_reason_for_add,
rde_data_alias_names,
rde_data_doc_reference_url,
rde_data_ci_owner,
rde_data_drp_class,
rde_data_last_cmdb_audit,
rde_data_owner_organization,
rde_data_security_category,
rde_data_security_class,
rde_data_nsa_restricted,
rde_data_criticity_of_application,
rde_data_url_on_key_user_link,
rde_data_nssr_scoping_approver_email,
rde_data_nssr_scoping_approver_details,
rde_data_purpose_function,
rde_data_ea_id,
rde_data_eccn,
rde_data_application_release_number,
rde_data_customer_downtime_contact_email,
rde_data_customer_downtime_contact_details,
rde_data_complexity,
rde_data_service_ci,
rde_data_affected_service,
rde_ci_owner_company,
sm_data_sourcing_accountable,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
application_type
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_name_app,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
rde_data_backup_policies,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
app_id,
application_productnumber,
rde_data_approval_workflow,
rde_data_acronym_name,
rde_data_legacy_id,
rde_data_application_information_link,
rde_data_business_area,
rde_data_business_subarea,
rde_data_business_stakeholder_email,
rde_data_business_stakeholder_details,
rde_data_business_stakeholder_organization,
rde_data_key_business_user,
rde_data_countries,
rde_data_active_user_count,
rde_data_user_display_languages,
rde_data_app_managed_by,
rde_data_ism_mgd,
rde_data_business_er_approver_email,
rde_data_business_er_approver_details,
rde_data_application_manager_email,
rde_data_application_manager_details,
rde_data_solution_lead_email,
rde_data_solution_lead_details,
sm_data_technical_owner_details,
rde_data_outsource_comments,
rde_data_core_program,
rde_data_sw_package_notes,
rde_data_sw_release_notes,
rde_data_dev_language_and_tools,
rde_data_architecture,
rde_data_database_notes,
rde_data_service_window_proposed,
rde_data_service_window_comment,
rde_data_application_lifecycle_status,
rde_data_target_solution,
rde_data_decomm_date,
rde_data_original_decomm_date,
rde_data_decomm_target_date,
rde_data_decomm_notes,
rde_data_pw_linked_to_network_logon,
rde_data_pwd_change_process,
rde_data_primary_helpdesk,
rde_data_er_tool,
rde_data_incident_reporting_tool,
rde_data_service_request_tool,
rde_data_date_added_to_portfolio,
rde_data_ovsd_id,
rde_data_assetctr_id,
rde_data_change_management_tool,
rde_data_knowledge_management_tool,
rde_data_ticket_volume_er,
rde_data_ticket_volume_incident,
rde_data_ticket_volume_request,
rde_data_ticket_volume_change,
rde_data_it_support_staff,
rde_data_documentation_quality,
rde_data_notes,
rde_data_incl_in_scorecard,
rde_data_book_close_impact,
rde_data_core_program_previous,
rde_data_reason_for_add,
rde_data_alias_names,
rde_data_doc_reference_url,
rde_data_ci_owner,
rde_data_drp_class,
rde_data_last_cmdb_audit,
rde_data_owner_organization,
rde_data_security_category,
rde_data_security_class,
rde_data_nsa_restricted,
rde_data_criticity_of_application,
rde_data_url_on_key_user_link,
rde_data_nssr_scoping_approver_email,
rde_data_nssr_scoping_approver_details,
rde_data_purpose_function,
rde_data_ea_id,
rde_data_eccn,
rde_data_application_release_number,
rde_data_customer_downtime_contact_email,
rde_data_customer_downtime_contact_details,
rde_data_complexity,
rde_data_service_ci,
rde_data_affected_service,
rde_ci_owner_company,
sm_data_sourcing_accountable,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
application_type
from ci
where ci_type = "logical_application";

show warnings;
commit;
select "insert of all logical applications completed.";


-- *******************************************************************************************************
-- copy of all business units
INSERT INTO
validation.business_unit
(
 business_criticality_level,
 city,
 country,
 data_adminstate,
 data_description,
 data_externalid,
 data_name,
 data_note,
 data_operationstate,
 data_origin,
 data_source,
 data_updated_by,
 digest,
 latitude,
 longitude,
 state,
 user_label,
 system_status_enum,
 environment_status_enum,
 system_status,
 environment_status,
 custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
sm_data_sourcing_accountable,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
sm_data_sourcing_accountable,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "business_unit";

show warnings;
commit;
select "insert of all business units completed.";

-- copy of datacenters
INSERT INTO
validation.datacenter
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
datacenter_status,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
datacenter_status,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "datacenter";

show warnings;
commit;
select "insert of all datacenter completed.";


-- copy of logical_group
INSERT INTO
validation.logical_group
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
logical_group_type,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
logical_group_type,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "logical_group";

show warnings;
commit;
select "insert of all logical groups completed.";


-- copy business service for catalog
INSERT INTO
validation.business_service_for_catalog
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
provider,
provision,
rde_data_approval_workflow,
rde_data_acronym_name,
rde_data_legacy_id,
rde_data_business_stakeholder_email,
rde_data_business_stakeholder_details,
rde_data_active_user_count,
rde_data_business_er_approver_email,
rde_data_business_er_approver_details,
rde_data_application_manager_email,
rde_data_application_manager_details,
rde_data_solution_lead_email,
rde_data_solution_lead_details,
sm_data_technical_owner_details,
rde_data_book_close_impact,
rde_data_alias_names,
rde_data_owner_organization,
rde_data_security_category,
rde_data_security_class,
rde_data_nsa_restricted,
rde_data_criticity_of_application,
rde_data_nssr_scoping_approver_email,
rde_data_nssr_scoping_approver_details,
rde_data_purpose_function,
rde_data_customer_downtime_contact_email,
rde_data_customer_downtime_contact_details,
rde_data_service_ci,
sm_data_sourcing_accountable,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
provider,
provision,
rde_data_approval_workflow,
rde_data_acronym_name,
rde_data_legacy_id,
rde_data_business_stakeholder_email,
rde_data_business_stakeholder_details,
rde_data_active_user_count,
rde_data_business_er_approver_email,
rde_data_business_er_approver_details,
rde_data_application_manager_email,
rde_data_application_manager_details,
rde_data_solution_lead_email,
rde_data_solution_lead_details,
sm_data_technical_owner_details,
rde_data_book_close_impact,
rde_data_alias_names,
rde_data_owner_organization,
rde_data_security_category,
rde_data_security_class,
rde_data_nsa_restricted,
rde_data_criticity_of_application,
rde_data_nssr_scoping_approver_email,
rde_data_nssr_scoping_approver_details,
rde_data_purpose_function,
rde_data_customer_downtime_contact_email,
rde_data_customer_downtime_contact_details,
rde_data_service_ci,
sm_data_sourcing_accountable,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "business_service_for_catalog";

show warnings;
commit;
select "insert of all business service for catalog completed.";



-- Copy of clusters
INSERT INTO
validation.cluster
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
instancescount,
vendor,
version,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
instancescount,
vendor,
version,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "cluster";

show warnings;
commit;
select "insert of all clusters completed.";





-- Copy of all sap systems
INSERT INTO
validation.sap_system
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
ip_address,
ip_domain,
license_exp_date,
license_number,
router,
system_number,
system_solman,
username,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
 city,
 country,
 data_adminstate,
 data_description,
 data_externalid,
 data_name,
 data_note,
 data_operationstate,
 data_origin,
 data_source,
 data_updated_by,
 digest,
 latitude,
 longitude,
 state,
 user_label,
 system_status_enum,
 environment_status_enum,
 system_status,
 environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
ip_address,
ip_domain,
license_exp_date,
license_number,
router,
system_number,
system_solman,
username,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "sap_system";

show warnings;
commit;
select "insert of all sap systems completed.";



-- Copy of all hosts
INSERT INTO
validation.host
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "host";

show warnings;
commit;
select "insert of all hots completed.";


-- Copy of disks
INSERT INTO
validation.disk
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
environment_status_enum,
system_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual,
disk_failures,
disk_size,
disk_type
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
environment_status_enum,
system_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual,
disk_failures,
disk_size,
disk_type
from ci
where ci_type = "disk";

show warnings;
commit;
select "insert of all disks completed.";



-- Copy of all software
INSERT INTO
validation.software
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual,
software_data,
software_installpath,
software_productid,
software_type,
software_vendor,
software_version
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual,
software_data,
software_installpath,
software_productid,
software_type,
software_vendor,
software_version
from ci
where ci_type = "software";

show warnings;
commit;
select "insert of all software completed.";



-- Copy of all clustergroups
INSERT INTO
validation.clustergroup
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "clustergroup";

show warnings;
commit;
select "insert of all cluster groups completed.";



-- Copy of all interface indexes
INSERT INTO
validation.interfaceindex
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual,
interfaceindex_adminstatus,
interfaceindex_index,
interfaceindex_operstatus,
interfaceindex_port,
interfaceindex_speed,
interfaceindex_type,
interfaceindex_usage,
interfaceindex_vendor,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
 city,
 country,
 data_adminstate,
 data_description,
 data_externalid,
 data_name,
 data_note,
 data_operationstate,
 data_origin,
 data_source,
 data_updated_by,
 digest,
 latitude,
 longitude,
 state,
 user_label,
 system_status_enum,
 environment_status_enum,
 system_status,
 environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual,
interfaceindex_adminstatus,
interfaceindex_index,
interfaceindex_operstatus,
interfaceindex_port,
interfaceindex_speed,
interfaceindex_type,
interfaceindex_usage,
interfaceindex_vendor,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "interfaceindex";

show warnings;
commit;
select "insert of all interface indexes completed.";



-- Copy of all ip's
INSERT INTO
validation.ip
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
credentials_id,
language,
isvirtual,
ip_address,
ip_dhcpdomainname,
ip_dnsname,
ip_domain,
ip_isbroadcast,
ip_isdhcp,
ip_ismanaged,
ip_netaddr,
ip_netclass,
ip_netmask,
ip_nettype,
ip_probename,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
credentials_id,
language,
isvirtual,
ip_address,
ip_dhcpdomainname,
ip_dnsname,
ip_domain,
ip_isbroadcast,
ip_isdhcp,
ip_ismanaged,
ip_netaddr,
ip_netclass,
ip_netmask,
ip_nettype,
ip_probename,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "ip";

show warnings;
commit;
select "insert of all IP completed.";



-- Copy of all interfaces
INSERT INTO
validation.interface
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
credentials_id,
language,
isvirtual,
interface_description,
interface_macaddr,
isPseudo,
l2help,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_duplex_settings
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
credentials_id,
language,
isvirtual,
interface_description,
interface_macaddr,
isPseudo,
l2help,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_duplex_settings
from ci
where ci_type = "interface";

show warnings;
commit;
select "insert of all interfaces completed.";



-- Copy of storagearrays
INSERT INTO
validation.storagearray
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual,
storagearray_ip,
storagearray_model,
storagearray_serialnumber,
storagearray_status,
storagearray_vendor,
storagearray_version,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual,
storagearray_ip,
storagearray_model,
storagearray_serialnumber,
storagearray_status,
storagearray_vendor,
storagearray_version,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "storagearray";

show warnings;
commit;
select "insert of all storage arrays completed.";

-- Copy of host nodes
INSERT INTO
validation.host_node
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
from ci
where ci_type = "host_node";

show warnings;
commit;
select "Copied host nodes.";





INSERT INTO
validation.lb
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
credentials_id,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
lb_features,
lb_redundantoperstatus,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
credentials_id,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
lb_features,
lb_redundantoperstatus,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "lb";

show warnings;
commit;

INSERT INTO
validation.router
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
 city,
 country,
 data_adminstate,
 data_description,
 data_externalid,
 data_name,
 data_note,
 data_operationstate,
 data_origin,
 data_source,
 data_updated_by,
 digest,
 latitude,
 longitude,
 state,
 user_label,
 system_status_enum,
 environment_status_enum,
 system_status,
 environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "router";

commit;

INSERT INTO
validation.switch
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "switch";

commit;

INSERT INTO
validation.switchrouter
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "switchrouter";

commit;

INSERT INTO
validation.application
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
rde_data_affected_service,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
rde_data_affected_service,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "application";

commit;