USE validation;

-- Copy of all logical applications
INSERT INTO
validation.webservice
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
service_name,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
service_name,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "webservice";

show warnings;
commit;
select "insert of all storage arrays completed.";

INSERT INTO
validation.activedirectory
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "activedirectory";

show warnings;
commit;
select "Inserts for activedirectory have been finished.";


-- Copy of 
INSERT INTO
validation.unix
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "unix";


show warnings;
commit;
select "Inserts for unix have been finished.";



INSERT INTO
validation.clusteredservice
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
from ci
where ci_type = "clusteredservice";

show warnings;
commit;
select "insert of clusteredservice";


INSERT INTO
validation.mainframe
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
mainframe_cpcmodel,
mainframe_cpcserial,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
mainframe_cpcmodel,
mainframe_cpcserial,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
from ci
where ci_type = "mainframe";

show warnings;
commit;
select "inserts of mainframe";


INSERT INTO
validation.terminalserver
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
from ci
where ci_type = "terminalserver";


show warnings;
commit;
select "insert of all terminal servers completed.";


INSERT INTO
validation.vmware_esx_server
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
from ci
where ci_type = "vmware_esx_server";


show warnings;
commit;
select "insert of all vmware esx servers completed.";

INSERT INTO
validation.nt
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
nt_mainprocessorspeed,
nt_processorsnumber,
nt_registeredowner,
nt_servicepack,
SP_URL,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
nt_mainprocessorspeed,
nt_processorsnumber,
nt_registeredowner,
nt_servicepack,
SP_URL,
hostnode_physicalmemory,
hostnode_mainprocessorspeed,
hostnode_mainprocessortype,
hostnode_processorsnumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to,
rde_data_inf_tape_drive_type,
rde_data_inf_tape_drive_number,
rde_data_inf_coverage_end_date,
rde_data_inf_maint_contract,
rde_data_inf_no_of_disks_x_disk_size,
rde_data_inf_admin_secondary_contact,
rde_data_inf_alias_names,
rde_data_inf_backup_information,
rde_data_inf_backup_media_server,
rde_data_inf_backup_mode,
rde_data_inf_backup_restartable,
rde_data_inf_backup_restore_procedures,
rde_data_inf_backup_retention,
rde_data_inf_backup_schedule,
rde_data_inf_backup_server,
rde_data_inf_backup_storage,
rde_data_inf_drp_class,
rde_data_inf_maint_window,
rde_data_inf_monitored_by,
rde_data_inf_os_time_zone,
rde_data_inf_purpose_function,
rde_data_inf_complexity,
rde_data_inf_contract_elements
from ci
where ci_type = "nt";


show warnings;
commit;
select "insert of all NT completed.";


INSERT INTO
validation.netdevice
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
credentials_id,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
document_list,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
credentials_id,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "netdevice";


show warnings;
commit;
select "insert of all netdevices completed.";


INSERT INTO
validation.chassis
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
chassis_model,
chassis_uniqueid,
chassis_vendor,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
 city,
 country,
 data_adminstate,
 data_description,
 data_externalid,
 data_name,
 data_note,
 data_operationstate,
 data_origin,
 data_source,
 data_updated_by,
 digest,
 latitude,
 longitude,
 state,
 user_label,
 system_status_enum,
 environment_status_enum,
 system_status,
 environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
chassis_model,
chassis_uniqueid,
chassis_vendor,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "chassis";


show warnings;
commit;
select "insert of all chassis completed.";


INSERT INTO
validation.firewall
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "firewall";


show warnings;
commit;
select "insert of all firewall completed.";


INSERT INTO
validation.ras
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "ras";


show warnings;
commit;
select "insert of all ras completed.";


INSERT INTO
validation.fcswitch
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
fcswitch_availableports,
fcswitch_connectedports,
fcswitch_freeports,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
host_biosuuid,
host_dnsname,
host_hostname,
host_iscomplete,
host_isdesktop,
host_isroute,
host_isvirtual,
host_key,
host_last_boot_time,
host_manufacturer,
host_model,
host_nnm_uid,
host_os,
host_osaccuracy,
host_osdomain,
host_osinstalltype,
host_osrelease,
host_osversion,
host_serialnumber,
host_servertype,
host_snmpsysname,
host_systemassettag,
host_vendor,
internal_name,
host_productnumber,
host_locationstring,
fcswitch_availableports,
fcswitch_connectedports,
fcswitch_freeports,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "fcswitch";


show warnings;
commit;
select "insert of all fc switches completed.";


INSERT INTO
validation.hostresource
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual
from ci
where ci_type = "hostresource";


show warnings;
commit;
select "insert of all host resources completed.";


INSERT INTO
validation.cpu
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
isvirtual,
core_number,
cpu_cid,
cpu_speed,
cpu_usage,
cpu_vendor
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
isvirtual,
core_number,
cpu_cid,
cpu_speed,
cpu_usage,
cpu_vendor
from ci
where ci_type = "cpu";



show warnings;
commit;
select "insert of all cpu's completed.";


INSERT INTO
validation.database
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
rde_data_affected_service,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
rde_data_affected_service,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "database";


show warnings;
commit;
select "insert of all databases completed.";


INSERT INTO
validation.db2
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
rde_data_affected_service,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
rde_data_affected_service,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "db2";


show warnings;
commit;
select "insert of all DB2 completed.";


INSERT INTO
validation.oracle
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
oracle_instancenumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
rde_data_affected_service,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
oracle_instancenumber,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
rde_data_affected_service,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "oracle";


show warnings;
commit;
select "insert of all oracle completed.";


INSERT INTO
validation.sqlserver
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_affected_service,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_affected_service,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "sqlserver";


show warnings;
commit;
select "insert of all sql servers completed.";


INSERT INTO
validation.sybase
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_affected_service,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
application_category,
application_ip,
application_path,
application_port,
application_timeout,
application_username,
application_version,
application_version_number,
has_config_files,
root_container_name,
vendor,
database_dbinstallpath,
database_dbport,
database_dbsid,
database_dbtype,
database_dbversion,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_affected_service,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "sybase";


show warnings;
commit;
select "insert of all sybase completed.";


INSERT INTO
validation.it_world
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit
from ci
where ci_type = "it_world";



show warnings;
commit;
select "insert of all IT World completed.";


INSERT INTO
validation.business
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
business_criticality_level
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
business_criticality_level
from ci
where ci_type = "business";



show warnings;
commit;
select "insert of all businesses completed.";



INSERT INTO
validation.line_of_business
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "line_of_business";



show warnings;
commit;
select "insert of all line of business completed.";


INSERT INTO
validation.location
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
location_id,
location_effectivedate,
location_enddate,
location_buildingtype,
location_occupancytype,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
location_id,
location_effectivedate,
location_enddate,
location_buildingtype,
location_occupancytype,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "location";



show warnings;
commit;
select "insert of all location completed.";


INSERT INTO
validation.logical_service
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "logical_service";


show warnings;
commit;
select "insert of all logical services completed.";


INSERT INTO
validation.person
(
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
email,
fax_phone,
full_name,
identification_key,
identification_type,
last_name,
office_phone,
title
)
SELECT
business_criticality_level,
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
email,
fax_phone,
full_name,
identification_key,
identification_type,
last_name,
office_phone,
title
from ci
where ci_type = "person";



show warnings;
commit;
select "insert of all persons completed.";


INSERT INTO
validation.`RDE_Maintenance Contract`
(
city,
country,
sm_data_sourcing_accountable,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
rde_report_procedure,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
rde_data_system_status,
environment_status,
rde_data_system_handle,
custom_attribute1,
custom_attribute2,
rde_data_support_type,
custom_attribute3,
rde_data_service_coverage,
rde_data_organization,
custom_attribute4,
rde_data_contract_id,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
business_criticality_level
)
SELECT
city,
country,
sm_data_sourcing_accountable,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
"NO uCMDB Label Mapping" as rde_report_procedure,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
"NO uCMDB Label Mapping" as `rde_data_system_status`,
environment_status,
"NO uCMDB Label Mapping" as `rde_data_system_handle`,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as rde_data_support_type,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as rde_data_service_coverage,
"NO uCMDB Label Mapping" as rde_data_organization,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as rde_data_contract_id,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
business_criticality_level
from ci
where ci_type = "RDE_Maintenance Contract";



show warnings;
commit;
select "insert of all RDE Maintenace Contract completed.";


INSERT INTO
validation.`RDE_Impacted Business`
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
rde_data_business_division,
custom_attribute1,
rde_data_business_group,
custom_attribute2,
rde_data_entity,
custom_attribute3,
rde_data_business_contact,
custom_attribute4,
rde_data_legal_unit,
custom_attribute5,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
business_criticality_level
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as rde_data_business_division,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as rde_data_business_group,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as rde_data_entity,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as rde_data_business_contact,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as rde_data_legal_unit,
"NO uCMDB Label Mapping" as custom_attribute5,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
business_criticality_level
from ci
where ci_type = "RDE_Impacted Business";


show warnings;
commit;
select "insert of all RDE Impacted Business completed.";


INSERT INTO
validation.`RDE_URL LINK`
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
business_criticality_level
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
business_criticality_level
from ci
where ci_type = "RDE_URL LINK";


show warnings;
commit;
select "insert of all RDE_URL LINK completed.";

INSERT INTO
validation.`system`
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language
from ci
where ci_type = "system";

show warnings;
commit;
select "insert of all system completed.";

INSERT INTO
validation.`applicationresource`
(
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
custom_attribute1,
custom_attribute2,
custom_attribute3,
custom_attribute4,
custom_attribute,
cmdbid,
markasdelete,
related_ciexternalid,
related_cit,
codepage,
language,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
)
SELECT
city,
country,
data_adminstate,
data_description,
data_externalid,
data_name,
data_note,
data_operationstate,
data_origin,
data_source,
data_updated_by,
digest,
latitude,
longitude,
state,
user_label,
system_status_enum,
environment_status_enum,
system_status,
environment_status,
"NO uCMDB Label Mapping" as custom_attribute1,
"NO uCMDB Label Mapping" as custom_attribute2,
"NO uCMDB Label Mapping" as custom_attribute3,
"NO uCMDB Label Mapping" as custom_attribute4,
"NO uCMDB Label Mapping" as custom_attribute,
cmdb_id,
"NO uCMDB Label Mapping" as markasdelete,
"NO uCMDB Label Mapping" as related_ciexternalid,
"NO uCMDB Label Mapping" as related_cit,
codepage,
language,
sm_data_sourcing_accountable,
sm_data_customer_downtime_contact,
sm_data_location_code,
sm_data_primary_incident_resolution_group,
sm_data_service_category_level_1,
sm_data_service_category_level_2,
sm_data_service_category_level_3,
sm_data_technical_owner,
sm_data_approver_groups,
sm_data_slo_group_enum,
sm_data_department_code,
rde_data_sox,
sm_data_change_coordinator_wgrp,
sm_data_change_manager_wgrp,
sm_data_change_impl_wgrp,
sm_data_change_supervisor_wrgp,
sm_data_sm_linkage,
sm_data_cfg_group,
rde_data_outsourced_to
from ci
where ci_type = "applicationresource";

show warnings;
commit;
select "insert of all applicationresource completed.";


