@ECHO OFF
REM ECHO ** PARAMETER : %1
REM ECHO ** PARAMETER : %2

IF "%1" == "" GOTO ABORT
IF "%2" == "" GOTO ABORT

IF NOT EXIST %1 GOTO NOTEXISTSSRC
IF NOT EXIST %2\NUL GOTO NOTEXISTS

MOVE /Y "%1" "%2" 

GOTO END

:NOTEXISTSSRC
ECHO ** SOURCE FILE %1 DOES NOT EXIST
GOTO END

:NOTEXISTS
ECHO ** DESTINATION FOLDER %2 DOES NOT EXIST 
GOTO END

:ABORT
ECHO ** FOUT BIJ MOVE %1 to %2
GOTO END

:END